language: ruby
script: bundle exec rspec spec
cache: bundler
rvm:
  - 2.0.0
  - 2.1.1
notifications:
  slack:
    secure: "aN7wc3+0EvwROw91z1OQK6zowdmRJESDWb541Q0PfmzMcQULAFtQKcJJ3UH/WlDle8aMVKfy3iqwZOJbDSLuPW7PXiHhiFlsSCOzQjxPDPYyeOooGBxEzfay5bWFxrYMUISRSi29mH6LEDEN2qYGHJaZbgjyNNzDrxsLJhS3clg="
  on_success: change
  on_failure: change
